image:
  file: Dockerfile
ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
tasks:
  - command: wget "http://eclipse.mirror.rafal.ca/oomph/epp/2019-12/R/eclipse-inst-linux64.tar.gz" && tar -xf *.tar.gz && mv eclipse-installer /tmp && cd /tmp/eclipse-installer && ./eclipse-inst
